### PR TITLE
Change esi formkey quoting

### PR DESCRIPTION
**Pull request by Cranke**
Changes quoting in Esi.php to fix Issue #17

### CODE REVIEW

**Comment by bbredewold** [comment]
Please merge this!

**Comment by RamonSmit** [comment]
:+1: This indeed fixed my problems. Thanks @Cranke

**Comment by kubaceg** [comment]
:+1: Thanks! Please merge it to main branch

**Comment by RamonSmit** [comment]
Well, looks like this repo is death like a jellyfish on the beach.

**Comment by RamonSmit** [comment]
YES :+1: finally... no more death templates :smile:

**Pull request merged**
